---
- name: Install basic packages
  hosts: all
  become: true
  tasks:
    - name: Install git
      apt:
        name: git
        state: present

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install vim
      apt:
        name: vim
        state: present
