---
- name: Install required packages
  hosts: all
  become: true
  tasks:
    - name: Install packages
      apt:
        name:
          - nginx
          - python3
          - python3-pip
        state: present
